// Minimal bug-finding lint gate (no style rules, no plugin dependencies).
// Run: npx eslint@10.12.0
export default [
  { ignores: ["node_modules/**", "dist/**", "build/**", "coverage/**"] },
  {
    files: ["lib/**/*.js", "bin/**/*", "bench/**/*.js", "demo/**/*.js", "test/**/*.js", "**/*.mjs"],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "module",
      globals: {
      process: "readonly",
      Buffer: "readonly",
      console: "readonly",
      setTimeout: "readonly",
      clearTimeout: "readonly",
      setInterval: "readonly",
      clearInterval: "readonly",
      setImmediate: "readonly",
      clearImmediate: "readonly",
      URL: "readonly",
      URLSearchParams: "readonly",
      TextEncoder: "readonly",
      TextDecoder: "readonly",
      AbortController: "readonly",
      AbortSignal: "readonly",
      fetch: "readonly",
      Headers: "readonly",
      Request: "readonly",
      Response: "readonly",
      FormData: "readonly",
      Blob: "readonly",
      structuredClone: "readonly",
      queueMicrotask: "readonly",
      performance: "readonly",
      atob: "readonly",
      btoa: "readonly",
      globalThis: "readonly",
      crypto: "readonly",
      EventTarget: "readonly",
      Event: "readonly",
      BroadcastChannel: "readonly",
      MessageChannel: "readonly",
      WebAssembly: "readonly",
      require: "readonly",
      module: "readonly",
      exports: "readonly",
      __dirname: "readonly",
      __filename: "readonly",
      window: "readonly",
      document: "readonly",
      navigator: "readonly",
      location: "readonly",
      localStorage: "readonly",
      sessionStorage: "readonly",
      alert: "readonly",
      confirm: "readonly",
      prompt: "readonly",
      requestAnimationFrame: "readonly",
      cancelAnimationFrame: "readonly",
      HTMLElement: "readonly",
      Element: "readonly",
      Node: "readonly",
      CustomEvent: "readonly",
      FileReader: "readonly",
      Image: "readonly",
      Audio: "readonly",
      WebSocket: "readonly",
      MutationObserver: "readonly",
      IntersectionObserver: "readonly",
      ResizeObserver: "readonly",
      indexedDB: "readonly",
      history: "readonly",
      getComputedStyle: "readonly",
      matchMedia: "readonly",
      DOMParser: "readonly",
      XMLHttpRequest: "readonly",
      Worker: "readonly",
      caches: "readonly",
      self: "readonly",
      IDBKeyRange: "readonly",
      customElements: "readonly"
      },
    },
    rules: {
    "no-undef": "error",
    "no-dupe-keys": "error",
    "no-dupe-args": "error",
    "no-dupe-else-if": "error",
    "no-duplicate-case": "error",
    "no-unreachable": "error",
    "no-const-assign": "error",
    "no-func-assign": "error",
    "no-class-assign": "error",
    "no-self-assign": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-redeclare": "error",
    "no-import-assign": "error",
    "no-invalid-regexp": "error",
    "no-sparse-arrays": "error",
    "use-isnan": "error",
    "valid-typeof": "error",
    "no-unused-private-class-members": "error"
    },
  },
];
